services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producao-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
